"""
Student Performance Prediction App
COMP6577001 – Machine Learning Final Project
BINUS University 2025/2026
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Student Performance Predictor",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .main { background-color: #f8f9fa; }
    .stMetric { background: white; border-radius: 12px; padding: 1rem; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
    .info-box  { background: #eaf4ff; border-left: 5px solid #3498db; padding: 1rem; border-radius: 8px; }
</style>
""", unsafe_allow_html=True)

    # .risk-high { background: #fff0f0; border-left: 5px solid #e74c3c; padding: 1rem; border-radius: 8px; }
    # .risk-low  { background: #f0fff4; border-left: 5px solid #27ae60; padding: 1rem; border-radius: 8px; }

# ── Load models ───────────────────────────────────────────────────────────────
MODEL_DIR = os.path.join(os.path.dirname(__file__), "..", "models")

@st.cache_resource
def load_models():
    # clf      = joblib.load(os.path.join(MODEL_DIR, "dropout_classifier.pkl"))
    reg      = joblib.load(os.path.join(MODEL_DIR, "exam_score_regressor.pkl"))
    features = joblib.load(os.path.join(MODEL_DIR, "features.pkl"))
    # return clf, reg, features
    return reg, features

# clf, reg, FEATURES = load_models()
reg, FEATURES = load_models()

# ── Sidebar ───────────────────────────────────────────────────────────────────

    # - 🔴 **Dropout Risk** classifier
    # | Decision Tree | Classifier | AUC=1.00 |
    # Two ML models:

with st.sidebar:
    st.image("https://socs.binus.ac.id/wp-content/uploads/2013/02/Logo-SoCS-Black-Blue.png", width=250)
    st.markdown("---")
    st.markdown("### 🎓 About")
    st.markdown("""
    **COMP6577001 – Machine Learning**  
    Final Project · AY 2025/2026  
    BINUS University
    
    ML model:
    - 📈 **Exam Score** regressor
    """)
    st.markdown("---")
    st.markdown("### 📊 Model Info")
    st.markdown("""
    | Model | Type | Score |
    |---|---|---|
    | Ridge Regression | Regressor | R²=0.87 |
    """)
    
    st.markdown("---")
    st.markdown("### ⚠️ Disclaimer")
    st.markdown("""
    The predictions generated by the model should **not be considered official, authoritative, or guaranteed forecasts** of actual exam performance. Model outputs are based on historical data patterns and may be affected by limitations in the dataset, assumptions made during training, and inherent prediction uncertainty.

    Users should **not use this application as a legitimate prognosis, evaluation tool, or basis for important academic decisions**. The results are intended solely to illustrate the application of machine learning techniques in an educational setting.
    """)

# ── Header ────────────────────────────────────────────────────────────────────
st.title("🎓 Student Performance Predictor")
# st.markdown("**Predict dropout risk and expected exam score** based on student profile data.")
st.markdown("**Predict expected exam score** based on student profile data.")
st.markdown("---")

# ── Input Form ────────────────────────────────────────────────────────────────
st.subheader("📋 Enter Student Profile")

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("#### 👤 Demographics")
    age    = st.slider("Age", 16, 28, 21)
    gender = st.selectbox("Gender", options=[0, 1, 2], format_func=lambda x: ["Female", "Male", "Other"][x])
    health_status = st.selectbox("Health Status", [0, 1, 2, 3],
                                  format_func=lambda x: ["Poor", "Fair", "Good", "Excellent"][x])

    st.markdown("#### 💼 Work & Activities")
    part_time_job = st.selectbox("Part-time Job", [0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
    extracurricular = st.selectbox("Extracurricular Activities", [0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
    extra_tuition   = st.selectbox("Extra Tuition", [0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
    social_activity = st.slider("Social Activity Level (0–10)", 0, 10, 5)

with col2:
    st.markdown("#### 📚 Academic")
    study_hours = st.slider("Study Hours / Day", 0.0, 12.0, 4.0, step=0.5)
    attendance  = st.slider("Attendance (%)", 0.0, 100.0, 80.0, step=1.0)
    previous_gpa = st.slider("Previous GPA (0.0 – 4.0)", 0.0, 4.0, 3.0, step=0.1)
    motivation  = st.slider("Motivation Level (0–10)", 0, 10, 6)
    parental_support = st.selectbox("Parental Support Level", [0, 1, 2, 3],
                                     format_func=lambda x: ["None", "Low", "Medium", "High"][x])

with col3:
    st.markdown("#### 🧠 Wellbeing")
    sleep_hours    = st.slider("Sleep Hours / Night", 3.0, 10.0, 7.0, step=0.5)
    mental_health  = st.slider("Mental Health Rating (0–10)", 0.0, 10.0, 6.0, step=0.5)
    stress_level   = st.slider("Stress Level (0–10)", 0.0, 10.0, 5.0, step=0.5)
    exam_anxiety   = st.slider("Exam Anxiety Score (0–100)", 0, 100, 40)
    screen_time    = st.slider("Screen Time (hrs/day)", 0.0, 12.0, 4.0, step=0.5)

# ── Predict ───────────────────────────────────────────────────────────────────
st.markdown("---")
predict_btn = st.button("🔮 Predict Now", type="primary", use_container_width=True)

if predict_btn:
    input_dict = {
        "age": age,
        "gender": gender,
        "study_hours_per_day": study_hours,
        "part_time_job": part_time_job,
        "attendance_percentage": attendance,
        "sleep_hours": sleep_hours,
        "mental_health_rating": mental_health,
        "extracurricular_participation": extracurricular,
        "previous_gpa": previous_gpa,
        "stress_level": stress_level,
        "social_activity": social_activity,
        "screen_time": screen_time,
        "parental_support_level": parental_support,
        "motivation_level": motivation,
        "exam_anxiety_score": exam_anxiety,
        "health_status": health_status,
        "extra_tuition": extra_tuition,
    }

    input_df = pd.DataFrame([input_dict])[FEATURES]

    # dropout_pred  = clf.predict(input_df)[0]
    # dropout_proba = clf.predict_proba(input_df)[0][1]
    exam_pred     = reg.predict(input_df)[0]
    exam_pred     = float(np.clip(exam_pred, 0, 100))

    st.subheader("🔍 Prediction Results")
    
    st.metric(
        "📝 Predicted Exam Score",
        f"{exam_pred:.1f} / 100"
    )
    
    # r1, r2, r3 = st.columns(3)

    # with r1:
    #     st.metric("🎯 Dropout Risk", "⚠️ AT RISK" if dropout_pred == 1 else "✅ LOW RISK")
    # with r2:
    #     st.metric("📊 Risk Probability", f"{dropout_proba * 100:.1f}%")
    # with r3:
    #     st.metric("📝 Predicted Exam Score", f"{exam_pred:.1f} / 100")

    st.markdown("")

    # Risk card
    # if dropout_pred == 1:
    #     st.markdown(f"""
    #     <div class="risk-high">
    #     <strong>⚠️ High Dropout Risk Detected</strong><br>
    #     This student has a <strong>{dropout_proba*100:.1f}%</strong> probability of dropout.
    #     Immediate academic intervention is recommended.
    #     </div>""", unsafe_allow_html=True)
    # else:
    #     st.markdown(f"""
    #     <div class="risk-low">
    #     <strong>✅ Low Dropout Risk</strong><br>
    #     This student has only a <strong>{dropout_proba*100:.1f}%</strong> chance of dropout.
    #     Keep monitoring and encourage continued engagement.
    #     </div>""", unsafe_allow_html=True)

    # st.markdown("")

    # Score interpretation
    if exam_pred >= 85:
        grade, color = "A (Excellent)", "#27ae60"
    elif exam_pred >= 70:
        grade, color = "B (Good)", "#2980b9"
    elif exam_pred >= 55:
        grade, color = "C (Fair)", "#f39c12"
    else:
        grade, color = "D/F (At Risk)", "#e74c3c"

    st.markdown(f"""
    <div class="info-box">
    <strong>📝 Exam Score Interpretation</strong><br>
    Predicted score: <strong style="font-size:1.2em">{exam_pred:.1f}</strong> → 
    Estimated grade: <strong style="color:{color}">{grade}</strong>
    </div>""", unsafe_allow_html=True)

    # Factor analysis
    st.markdown("---")
    st.subheader("📌 Key Factor Analysis")
    fc1, fc2 = st.columns(2)
    with fc1:
        st.markdown("**Positive Factors:**")
        pos = []
        if study_hours >= 5:    pos.append(f"✅ High study hours ({study_hours}h/day)")
        if attendance >= 80:    pos.append(f"✅ Good attendance ({attendance:.0f}%)")
        if previous_gpa >= 3.0: pos.append(f"✅ Strong previous GPA ({previous_gpa:.1f})")
        if mental_health >= 6:  pos.append(f"✅ Good mental health ({mental_health}/10)")
        if motivation >= 6:     pos.append(f"✅ High motivation ({motivation}/10)")
        if parental_support >= 2: pos.append("✅ Adequate parental support")
        st.markdown("\n".join(pos) if pos else "_No notable positives identified_")

    with fc2:
        st.markdown("**Risk Factors:**")
        neg = []
        if study_hours < 3:     neg.append(f"❌ Low study hours ({study_hours}h/day)")
        if attendance < 70:     neg.append(f"❌ Low attendance ({attendance:.0f}%)")
        if stress_level >= 7:   neg.append(f"❌ High stress ({stress_level}/10)")
        if mental_health < 4:   neg.append(f"❌ Poor mental health ({mental_health}/10)")
        if exam_anxiety >= 70:  neg.append(f"❌ High exam anxiety ({exam_anxiety})")
        if sleep_hours < 6:     neg.append(f"❌ Insufficient sleep ({sleep_hours}h)")
        st.markdown("\n".join(neg) if neg else "_No notable risk factors identified_")

# ── Footer ────────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown(
    "<center><small>COMP6577001 Machine Learning · BINUS University · AY 2025/2026 | "
    "Built with Scikit-learn & Streamlit</small></center>",
    unsafe_allow_html=True
)
