"""
Student Performance Prediction App
COMP6577001 – Machine Learning Final Project
BINUS University 2025/2026
"""

import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st

# ── Page Config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Student Performance Predictor",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Custom CSS (Theme Aware) ────────────────────────────────────────────────
st.markdown("""
<style>

.stMetric {
    border-radius: 16px;
    padding: 0.75rem;
    border: 1px solid rgba(128,128,128,0.2);
    backdrop-filter: blur(8px);
}

.info-box {
    background: rgba(52,152,219,0.12);
    border-left: 5px solid #3498db;
    padding: 1rem;
    border-radius: 12px;
    color: inherit;
}

.performance-card {
    padding: 1.5rem;
    border-radius: 18px;
    border: 1px solid rgba(128,128,128,0.2);
    background: linear-gradient(
        135deg,
        rgba(52,152,219,0.15),
        rgba(155,89,182,0.12)
    );
    color: inherit;
    margin-top: 1rem;
}

.performance-title {
    font-size: 1.2rem;
    font-weight: 700;
    margin-bottom: 0.8rem;
}

.performance-score {
    font-size: 2rem;
    font-weight: 800;
}

.recommendation-card {
    margin-top: 1rem;
    padding: 1.2rem;
    border-radius: 16px;
    border: 1px solid rgba(128,128,128,0.2);
    background: rgba(46,204,113,0.08);
    color: inherit;
}

.factor-card {
    padding: 1rem;
    border-radius: 12px;
    border: 1px solid rgba(128,128,128,0.15);
}

</style>
""", unsafe_allow_html=True)

# ── Load Models ─────────────────────────────────────────────────────────────
MODEL_DIR = os.path.join(os.path.dirname(__file__), "..", "models")


@st.cache_resource
def load_models():
    reg = joblib.load(os.path.join(MODEL_DIR, "exam_score_regressor.pkl"))
    features = joblib.load(os.path.join(MODEL_DIR, "features.pkl"))
    return reg, features


reg, FEATURES = load_models()

# ── Sidebar ─────────────────────────────────────────────────────────────────
with st.sidebar:
    st.image(
        "https://socs.binus.ac.id/wp-content/uploads/2013/02/Logo-SoCS-Black-Blue.png",
        width=250
    )

    st.markdown("---")

    st.markdown("### 🎓 About")
    st.markdown("""
    **COMP6577001 – Machine Learning**
    Final Project · AY 2025/2026
    BINUS University

    ML model:
    - 📈 **Exam Score Regressor**
    """)

    st.markdown("---")

    st.markdown("### 📊 Model Info")
    st.markdown("""
    | Model | Type | Score |
    |---|---|---|
    | Ridge Regression | Regressor | R²=0.87 |
    """)

    st.markdown("---")

    st.markdown("### ⚠️ Disclaimer")
    st.markdown("""
    The predictions generated by the model should **not be considered official,
    authoritative, or guaranteed forecasts** of actual exam performance.

    Model outputs are based on historical data patterns and may be affected by
    limitations in the dataset, assumptions made during training, and inherent
    prediction uncertainty.

    Users should **not use this application as a legitimate prognosis,
    evaluation tool, or basis for important academic decisions**.

    The results are intended solely to illustrate the application of machine
    learning techniques in an educational setting.
    """)

# ── Header ──────────────────────────────────────────────────────────────────
st.title("🎓 Student Performance Predictor")

st.markdown(
    "**Predict expected exam score based on student profile data.**"
)

st.markdown("---")

# ── Input Form ──────────────────────────────────────────────────────────────
st.subheader("📋 Enter Student Profile")

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("#### 👤 Demographics")

    age = st.slider("Age", 16, 28, 21)

    gender = st.selectbox(
        "Gender",
        [0, 1, 2],
        format_func=lambda x: ["Female", "Male", "Other"][x]
    )

    health_status = st.selectbox(
        "Health Status",
        [0, 1, 2, 3],
        format_func=lambda x: ["Poor", "Fair", "Good", "Excellent"][x]
    )

    st.markdown("#### 💼 Work & Activities")

    part_time_job = st.selectbox(
        "Part-time Job",
        [0, 1],
        format_func=lambda x: "No" if x == 0 else "Yes"
    )

    extracurricular = st.selectbox(
        "Extracurricular Activities",
        [0, 1],
        format_func=lambda x: "No" if x == 0 else "Yes"
    )

    extra_tuition = st.selectbox(
        "Extra Tuition",
        [0, 1],
        format_func=lambda x: "No" if x == 0 else "Yes"
    )

    social_activity = st.slider(
        "Social Activity Level (0–10)",
        0,
        10,
        5
    )
with col2:
    st.markdown("#### 📚 Academic")

    study_hours = st.slider(
        "Study Hours / Day",
        0.0,
        12.0,
        4.0,
        step=0.5
    )

    attendance = st.slider(
        "Attendance (%)",
        0.0,
        100.0,
        80.0,
        step=1.0
    )

    previous_gpa = st.slider(
        "Previous GPA (0.0 – 4.0)",
        0.0,
        4.0,
        3.0,
        step=0.1
    )

    motivation = st.slider(
        "Motivation Level (0–10)",
        0,
        10,
        6
    )

    parental_support = st.selectbox(
        "Parental Support Level",
        [0, 1, 2, 3],
        format_func=lambda x: ["None", "Low", "Medium", "High"][x]
    )

with col3:
    st.markdown("#### 🧠 Wellbeing")

    sleep_hours = st.slider(
        "Sleep Hours / Night",
        3.0,
        10.0,
        7.0,
        step=0.5
    )

    mental_health = st.slider(
        "Mental Health Rating (0–10)",
        0.0,
        10.0,
        6.0,
        step=0.5
    )

    stress_level = st.slider(
        "Stress Level (0–10)",
        0.0,
        10.0,
        5.0,
        step=0.5
    )

    exam_anxiety = st.slider(
        "Exam Anxiety Score (0–100)",
        0,
        100,
        40
    )

    screen_time = st.slider(
        "Screen Time (hrs/day)",
        0.0,
        12.0,
        4.0,
        step=0.5
    )

# ── Prediction Button ───────────────────────────────────────────────────────
st.markdown("---")

predict_btn = st.button(
    "🔮 Predict Now",
    type="primary",
    use_container_width=True
)

if predict_btn:

    input_dict = {
        "age": age,
        "gender": gender,
        "study_hours_per_day": study_hours,
        "part_time_job": part_time_job,
        "attendance_percentage": attendance,
        "sleep_hours": sleep_hours,
        "mental_health_rating": mental_health,
        "extracurricular_participation": extracurricular,
        "previous_gpa": previous_gpa,
        "stress_level": stress_level,
        "social_activity": social_activity,
        "screen_time": screen_time,
        "parental_support_level": parental_support,
        "motivation_level": motivation,
        "exam_anxiety_score": exam_anxiety,
        "health_status": health_status,
        "extra_tuition": extra_tuition,
    }

    input_df = pd.DataFrame([input_dict])[FEATURES]

    exam_pred = reg.predict(input_df)[0]
    exam_pred = float(np.clip(exam_pred, 0, 100))

    if exam_pred >= 85:
        grade = "A (Excellent)"
        level = "Outstanding"
        color = "#27ae60"

    elif exam_pred >= 70:
        grade = "B (Good)"
        level = "Strong"
        color = "#3498db"

    elif exam_pred >= 55:
        grade = "C (Fair)"
        level = "Average"
        color = "#f39c12"

    else:
        grade = "D/F (At Risk)"
        level = "Needs Improvement"
        color = "#e74c3c"

    st.subheader("🔍 Prediction Results")

    c1, c2 = st.columns([2, 1])

    with c1:
        st.metric(
            "📝 Predicted Exam Score",
            f"{exam_pred:.1f} / 100"
        )

    with c2:
        st.metric(
            "🏆 Estimated Grade",
            grade.split()[0]
        )
    st.markdown(
            f"""
            <div class="performance-card">

            <div class="performance-title">
            📊 Performance Report
            </div>

            <div class="performance-score" style="color:{color}">
            {exam_pred:.1f}/100
            </div>

            <b>Estimated Grade:</b> {grade}<br>
            <b>Performance Category:</b> {level}

            </div>
            """,
            unsafe_allow_html=True
        )

    if exam_pred >= 85:
        summary = """
        🌟 The model predicts excellent academic performance. The student profile
        reflects strong academic habits, supportive learning conditions, and
        characteristics commonly associated with high achievement. Maintaining
        current study routines and wellbeing practices should help sustain
        this level of success.
        """

    elif exam_pred >= 70:
        summary = """
        📚 The student is expected to perform well academically. Current
        indicators suggest a solid foundation for success, though targeted
        improvements in weaker areas could further increase performance and
        potentially elevate results into the highest grade category.
        """

    elif exam_pred >= 55:
        summary = """
        ⚠️ The prediction suggests moderate performance. While the student is
        likely capable of passing comfortably, there are opportunities to
        improve consistency, study effectiveness, attendance, or wellbeing.
        Focused improvements could lead to meaningful score increases.
        """

    else:
        summary = """
        🚨 The prediction indicates potential academic challenges. Several
        factors may be limiting expected performance, including study habits,
        attendance, stress, sleep quality, or exam anxiety. Early intervention
        and structured support are strongly recommended.
        """

    st.markdown(
        f"""
        <div class="recommendation-card">
        <h4>📝 Prediction Summary</h4>
        <p>{summary}</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown("---")
    st.subheader("📌 Key Factor Analysis")

    fc1, fc2 = st.columns(2)

    with fc1:
        st.markdown("### ✅ Positive Factors")

        positives = []

        if study_hours >= 5:
            positives.append(f"High study hours ({study_hours}h/day)")

        if attendance >= 80:
            positives.append(f"Good attendance ({attendance:.0f}%)")

        if previous_gpa >= 3.0:
            positives.append(f"Strong previous GPA ({previous_gpa:.1f})")

        if mental_health >= 6:
            positives.append(f"Good mental health ({mental_health}/10)")

        if motivation >= 6:
            positives.append(f"High motivation ({motivation}/10)")

        if parental_support >= 2:
            positives.append("Adequate parental support")

        if positives:
            for item in positives:
                st.success(item)
        else:
            st.info("No notable positive factors identified.")
    with fc2:
        st.markdown("### ⚠️ Risk Factors")

        risks = []

        if study_hours < 3:
            risks.append(f"Low study hours ({study_hours}h/day)")

        if attendance < 70:
            risks.append(f"Low attendance ({attendance:.0f}%)")

        if stress_level >= 7:
            risks.append(f"High stress ({stress_level}/10)")

        if mental_health < 4:
            risks.append(f"Poor mental health ({mental_health}/10)")

        if exam_anxiety >= 70:
            risks.append(f"High exam anxiety ({exam_anxiety})")

        if sleep_hours < 6:
            risks.append(f"Insufficient sleep ({sleep_hours}h)")

        if risks:
            for item in risks:
                st.warning(item)
        else:
            st.info("No notable risk factors identified.")

    recommendations = []

    if study_hours < 4:
        recommendations.append(
            "📖 Increase daily study time and follow a structured revision schedule."
        )

    if attendance < 80:
        recommendations.append(
            "🏫 Improve attendance to strengthen understanding of course materials."
        )

    if sleep_hours < 7:
        recommendations.append(
            "😴 Aim for 7–9 hours of sleep to improve memory retention and focus."
        )

    if stress_level >= 7:
        recommendations.append(
            "🧘 Practice stress-management techniques such as exercise, mindfulness, or time planning."
        )

    if exam_anxiety >= 70:
        recommendations.append(
            "🎯 Use mock exams and preparation strategies to reduce exam anxiety."
        )

    if mental_health < 5:
        recommendations.append(
            "💙 Prioritize mental wellbeing and seek support when necessary."
        )

    if motivation < 5:
        recommendations.append(
            "🚀 Set smaller achievable learning goals to improve motivation."
        )

    if not recommendations:
        recommendations.append(
            "🌟 No major concerns detected. Continue maintaining current academic and wellbeing habits."
        )

    st.markdown("---")
    st.subheader("🎯 Recommended Actions")

    for recommendation in recommendations:
        st.markdown(f"- {recommendation}")

# ── Footer ──────────────────────────────────────────────────────────────────
st.markdown("---")

st.markdown(
    """
    <center>
    <small>
    COMP6577001 Machine Learning · BINUS University · AY 2025/2026 |
    Built with Scikit-learn & Streamlit
    </small>
    </center>
    """,
    unsafe_allow_html=True
)